### ISSUE TITLE
doc: wrong command in slow event loop tutorial

### ISSUE THREAD

**Issue by ThePrez** [clinicjs/node-clinic-doctor-examples#15]
On this page:
https://clinicjs.org/documentation/doctor/05-fixing-event-loop-problem/
It says to create a flame graph via:
`clinic flame --on-port 'autocannon localhost:$PORT' -- node slow-io`

But the command should perhaps be:
`clinic flame --on-port 'autocannon localhost:$PORT' -- node slow-event-loop`

Not sure if this is the proper place to report possible issues with the web site, so apologies if this is misplaced. Thanks!

**Comment by harsh-sri** [comment]
Just landed here to report same issue 👍

**Comment by RafaelGSS** [comment]
Which Node.js version are you using?
